apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: pytorch-single-cifar10
  namespace: default
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - name: pytorch
            image: pytorch-distributed-training:latest
            imagePullPolicy: Never
            env:
            - name: MINIO_ENDPOINT
              value: "minio.minio.svc.cluster.local:9000"
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow.mlflow.svc.cluster.local:5000"
            resources:
              limits:
                cpu: "2"
                memory: "3Gi"
              requests:
                cpu: "1"
                memory: "2Gi"