apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: cifar10-classifier
  namespace: default
spec:
  predictor:
    containers:
    - name: kserve-container
      image: cifar10-inference:latest
      imagePullPolicy: Never
      ports:
      - containerPort: 8080
        protocol: TCP
      resources:
        requests:
          cpu: "200m"
          memory: "1Gi"
        limits:
          cpu: "500m"
          memory: "1.5Gi"